"""initial schema

Revision ID: 0a1e3fafd37f
Revises: 
Create Date: 2026-04-01 19:27:43.852065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a1e3fafd37f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('competitors_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_seeds_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_name'), 'experiment', ['name'], unique=True)
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('isolation', 'aggregate', name='runmode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_entity_id'), 'run', ['entity_id'], unique=False)
    op.create_index(op.f('ix_run_experiment_id'), 'run', ['experiment_id'], unique=False)
    op.create_table('demand_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('search_volume', sa.Float(), nullable=True),
    sa.Column('trend_velocity', sa.Float(), nullable=True),
    sa.Column('related_queries_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geographic_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_signal_run_id'), 'demand_signal', ['run_id'], unique=False)
    op.create_table('divergence_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('demand_llm_alignment_score', sa.Float(), nullable=False),
    sa.Column('divergence_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cross_query_stability', sa.Float(), nullable=False),
    sa.Column('average_recommendation_rank', sa.Float(), nullable=True),
    sa.Column('mention_type_distribution_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probes_included', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divergence_score_entity_id'), 'divergence_score', ['entity_id'], unique=False)
    op.create_index(op.f('ix_divergence_score_run_id'), 'divergence_score', ['run_id'], unique=False)
    op.create_table('query_probe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('query_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('probed_at', sa.DateTime(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_persona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expertise_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stated_use_case', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('system_prompt_variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prior_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_probe_run_id'), 'query_probe', ['run_id'], unique=False)
    op.create_index('ix_query_probe_run_variant', 'query_probe', ['run_id', 'query_variant'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('cited_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_recency', sa.DateTime(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_mention_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['query_probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_entry_id'), 'citation', ['entry_id'], unique=False)
    op.create_table('data_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('signal_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=True),
    sa.Column('signal_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('collector_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collector_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['query_probe.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_point_entity_id'), 'data_point', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_point_entry_id'), 'data_point', ['entry_id'], unique=False)
    op.create_index(op.f('ix_data_point_experiment_id'), 'data_point', ['experiment_id'], unique=False)
    op.create_index('ix_data_point_family_key', 'data_point', ['signal_family', 'signal_key'], unique=False)
    op.create_index(op.f('ix_data_point_run_id'), 'data_point', ['run_id'], unique=False)
    op.create_index(op.f('ix_data_point_signal_family'), 'data_point', ['signal_family'], unique=False)
    op.create_index(op.f('ix_data_point_signal_key'), 'data_point', ['signal_key'], unique=False)
    op.create_table('llm_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_rank', sa.Integer(), nullable=True),
    sa.Column('mention_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phrasing_sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_of_mention', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('co_mentioned_entities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_sensitivity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['query_probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_signal_entry_id'), 'llm_signal', ['entry_id'], unique=False)
    op.create_index('ix_llm_signal_entry_mention', 'llm_signal', ['entry_id', 'mention_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_signal_entry_mention', table_name='llm_signal')
    op.drop_index(op.f('ix_llm_signal_entry_id'), table_name='llm_signal')
    op.drop_table('llm_signal')
    op.drop_index(op.f('ix_data_point_signal_key'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_signal_family'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_run_id'), table_name='data_point')
    op.drop_index('ix_data_point_family_key', table_name='data_point')
    op.drop_index(op.f('ix_data_point_experiment_id'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_entry_id'), table_name='data_point')
    op.drop_index(op.f('ix_data_point_entity_id'), table_name='data_point')
    op.drop_table('data_point')
    op.drop_index(op.f('ix_citation_entry_id'), table_name='citation')
    op.drop_table('citation')
    op.drop_index('ix_query_probe_run_variant', table_name='query_probe')
    op.drop_index(op.f('ix_query_probe_run_id'), table_name='query_probe')
    op.drop_table('query_probe')
    op.drop_index(op.f('ix_divergence_score_run_id'), table_name='divergence_score')
    op.drop_index(op.f('ix_divergence_score_entity_id'), table_name='divergence_score')
    op.drop_table('divergence_score')
    op.drop_index(op.f('ix_demand_signal_run_id'), table_name='demand_signal')
    op.drop_table('demand_signal')
    op.drop_index(op.f('ix_run_experiment_id'), table_name='run')
    op.drop_index(op.f('ix_run_entity_id'), table_name='run')
    op.drop_table('run')
    op.drop_index(op.f('ix_experiment_name'), table_name='experiment')
    op.drop_table('experiment')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
