"""add perturbation_index to query_probe

Revision ID: d9cca56c69b2
Revises: 0a1e3fafd37f
Create Date: 2026-04-06 19:21:36.030667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9cca56c69b2'
down_revision: Union[str, None] = '0a1e3fafd37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_probe', sa.Column('perturbation_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_probe', 'perturbation_index')
    # ### end Alembic commands ###
